### ISSUE TITLE
Conversion issue of Pythonnet for Enum class

### ISSUE THREAD

**Issue by LeeDongGeon1996** [DaveSkender/Stock.Indicators.Python#13]
## The problem

  - Cannot pass Python Enum as C# Enum.
  - Pythonnet automatically converts C# Enums to `int`.
  - It seems like 'Pythonnet' is still trying to fix this issue. They said this problem will be fixed in version 3.0 and I think we cannot wait for it. The milestone for version 3.0 indicates  41% yet. 

Error message(s):
In Macbook Air(M1), Pythonnet uses Mono runtime for .Net.
Error messages are not quite helpful...

```bash
=================================================================
        Native Crash Reporting
=================================================================
Got a segv while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
        Native stacktrace:
=================================================================
        0x10c33cd75 - /Users/<username>/opt/anaconda3/envs/skender/lib/libmonosgen-2.0.1.dylib : mono_dump_native_crash_info
        0x10c2d7b8e - /Users/<username>/opt/anaconda3/envs/skender/lib/libmonosgen-2.0.1.dylib : mono_handle_native_crash
        0x10c33782b - /Users/<username>/opt/anaconda3/envs/skender/lib/libmonosgen-2.0.1.dylib : altstack_handle_and_restore

...skip...
```

## To Reproduce

1. Checkout to the branch, `feat/support-candlepart-sma` in my forked repo.
2. Run `pytest -svr A`

## Related Indicators
 - Williams
 - EMA
 - Stoch  Oscillator
 - Beta
 - ZigZag
 - Chandelier
 - MaEnvelopes
 - Pivot Points
 - Pivots

**Comment by cryptocoinserver** [comment]
They published v3 as alpha: https://github.com/pythonnet/pythonnet/issues/1513#issuecomment-974087411
`"I have published the current master version as alpha1 to pypi."`

**Comment by LeeDongGeon1996** [comment]
@cryptocoinserver Thank you for letting me know! I'll try with it when I get a moment in a short time.

**Comment by LeeDongGeon1996** [comment]
The preview of pythonnet still can not call correct overloaded function with Enum arguments, though Enum is not auto-converted to int anymore.

**Comment by DaveSkender** [comment]
Let’s just keep an eye it to see where the end up.  We can focus on the more dominant indicator methods. The overloads are mostly used to add extra features that are not as important or common.

**Comment by LeeDongGeon1996** [comment]
Agree with that.

**Comment by DaveSkender** [comment]
I just had a random thought.  Can we accept a `string` parameter and the have some sort of mapping internally, or is it that we simply cannot call the DLL at all when `enum` is specified?

**Comment by LeeDongGeon1996** [comment]
> is it that we simply cannot call the DLL at all when enum is specified?

For now, it is.

> Can we accept a string parameter and then have some sort of mapping internally

Yes, this can be one of the good workarounds, but the mapping has to be done inside the DLL. For the wrapper users, I can make them just use Enum having str value.

**Comment by DaveSkender** [comment]
If we add fixed integer values for these `enum` in the DLL then it might be possible for the wrapper to just map from `string` to these fixed `int` values without further mapping in the DLL?  might be worth an experiment.

does Python have an equivalent concept for `enum`?

**Comment by LeeDongGeon1996** [comment]
Yeah, if C# interface can accept `int` instead of `Enum`, the wrapper will be able to support it as Enum on Python user level. But [the milestone for 3.0.0](https://github.com/pythonnet/pythonnet/milestone/6) indicates 91% of progress and it includes all fixes of our problem. How about waiting a bit more until we wrap the rests?

**Comment by DaveSkender** [comment]
Yes, waiting is fine, not urgent.  I only mentioned it as I was browsing open issues.

**Comment by LeeDongGeon1996** [comment]
I just have checked methods with Enum parameter again and found that most of them are not overloaded. Then, it will be able to support Enum parameter in next release.
