### ISSUE TITLE
Marubozu with CandleResult

### ISSUE THREAD

**Issue by LeeDongGeon1996** [DaveSkender/Stock.Indicators.Python#168]
@DaveSkender I'm going to wrap Marubozu indicator, and I heard that you were refactoring it, is it available now?

And Marubozu returns `CandleResult`, including `CandleProperties`. So I'm also need to wrap `CandleProperties`. There are getters and setters for the properties of `CandleProperties`, for example, `Size` is calculated by `High - Low` when the moments it's called. Then, how does getter work once after `Size` is allocated with new values via setter method.

**Comment by DaveSkender** [comment]
I can probably simplify this `CandleProperties` class a bit.  Since many of those are calculated values, it may not need a public setter.

**Comment by DaveSkender** [comment]
It's also okay to hold off on these candlestick patterns.  I have both Marubozu and Doji in Preview status, so there still a chance a few things will change with our approach.

**Comment by LeeDongGeon1996** [comment]
> Yes, it's in v1.22.1. I can probably simplify this `CandleProperties` class a bit. Since many of those are calculated values, it may not need a public setter.

Oh, sorry. I thought that properties of `CandleProperties` have setters, but it doesn't.

**Comment by LeeDongGeon1996** [comment]
Then, please reopen or create new issue when you have changes on Marubozu :)
