### ISSUE TITLE
Manual DLL update in Piplines

### ISSUE THREAD

**Issue by LeeDongGeon1996** [DaveSkender/Stock.Indicators.Python#180]
We should consider updating DLL manually. In Piplines, using the latest DLL automatically can cause failure on tests because the DLL is not updated automatically in development environment. And that old DLL is used when new feature is committed. This interrupts tests for new feature and forces to order tasks to pass testcase.

**Comment by DaveSkender** [comment]
We’ll, it ensures that an official production copy is used (same version that was sent to NuGet) + it reminds us that it needs to be updated regularly, when it breaks 😀.

I’m okay with manual-only if those two condition can still be met.

**Comment by LeeDongGeon1996** [comment]
Yeah, above two conditions are important, but this wrapper is still catching up C# implementation. So sometimes these condition disturb adding new feature(like #178). It would be also good if we enable auto-update dll after v1.0

**Comment by LeeDongGeon1996** [comment]
Almost caught up C# implementation, so it's obsolete.
