### ISSUE TITLE
KVO docs typo

### ISSUE THREAD

**Issue by DaveSkender** [DaveSkender/Stock.Indicators.Python#227]
Documented KVO method should be fixed and not reflect Keltner.  Typo.  We'll need to also review the parameters and for other missing items while we taking a look.

> is there a reason why the function for the KVO is called get_keltner() and not e.g. get_klinger()? See here: https://daveskender.github.io/Stock.Indicators.Python/indicators/Kvo/#content
>
>Thanks,
>Andy

_Originally posted by @August1328 in https://github.com/DaveSkender/Stock.Indicators/discussions/446#discussioncomment-2707700_

**Comment by LeeDongGeon1996** [comment]
@August1328 Please let us know, if you'd like to contribute on this. We can wait for it, if you need time to learn GitHub.

**Comment by DaveSkender** [comment]
Might be good to also add a note in the Guide about dataframe conversion.  That seems to be a common thing.  @LeeDongGeon1996 is dataframe something we want to accept as an alternative input form?

**Comment by LeeDongGeon1996** [comment]
Right. In most of use-cases in Python, people use Pandas dataframe, so It would be good to add in Guide.
Actually, I'm worrying about performance to convert them, so thinking about C-extension for Python to convert them faster.
 > While Python is a great language and a pleasure to code in, its dynamic nature results in overhead that can cause some code ( i.e. raw computations inside of for loops) to be up 10-100 times slower than equivalent code written in a static compiled language. 
*From Numpy docs: https://numpy.org/doc/stable/user/c-info.python-as-glue.html#calling-other-compiled-libraries-from-python)*

> `dataframe` consists of `1D-array` of Numpy internally.

Do you think it is the case of above?
