### ISSUE TITLE
error: "PeriodSize" is not defined

### ISSUE THREAD

**Issue by DaveSkender** [DaveSkender/Stock.Indicators.Python#244]
I wrote the pivot points code with python in vscode but vscode had some error in indicator parameter defining.
![p1](https://user-images.githubusercontent.com/110600525/183849884-f33228ee-3e66-486d-9fbb-599f604c335d.JPG)

What's my mistake?

_Originally posted by @Gadirino in https://github.com/DaveSkender/Stock.Indicators/discussions/274#discussioncomment-3364313_

**Comment by DaveSkender** [comment]
@LeeDongGeon1996 have a moment to take look?

**Comment by LeeDongGeon1996** [comment]
@Gadirino  Hi, thank you for reporting. I think it needs to be updated for better UX.
In your case, this would be the solution. :)
`from stock_indicators.indicators.common.enums import PeriodSize, PivotPointType`

**Comment by Gadirino** [comment]
Hi @LeeDongGeon1996 @DaveSkender 
Thank you for your answers.
