### ISSUE TITLE
add prerequisite installs to documentation

### ISSUE THREAD

**Issue by DaveSkender** [DaveSkender/Stock.Indicators.Python#255]
As a follow to #254, add a list of things to install with links to download, to the "getting started" portion of the documentation.

**Comment by LeeDongGeon1996** [comment]
No doubt that it's important issue for our user. But, based on my experience, it's not quite easy to troubleshoot for installing pythonnet v2.x.x(Even [their docs](https://github.com/pythonnet/pythonnet/wiki/Troubleshooting-on-Windows,-Linux,-and-OSX) are complicated). And I think it has become very improved on v3.x.x, on which our next version dependent. With that said, I think it's better to release current dev version and docs(v0.9.0) asap than writing docs for current version(v0.8.1).

**Comment by DaveSkender** [comment]
Sounds good to me
