### ISSUE TITLE
ZigZag Fatal error. System.AccessViolationException: Attempted to read or write protected memory.

### ISSUE THREAD

**Issue by vincehayek** [DaveSkender/Stock.Indicators.Python#295]
Hello,

I am using the ZigZag indicator exactly as described here
https://python.stockindicators.dev/indicators/ZigZag/#content

`    quotes = [Quote(d,o,h,l,c,v) for d,o,h,l,c,v in zip(df['date'], df['open'], df['high'], df['low'], df['close'],df['vol'])]`
   
`     zigzag_objects = indicators.get_zig_zag(quotes, EndType.HIGH_LOW, change)`

I  am inputting a DataFrame and if it's too large (beyond 20K rows), I'm getting increasing chances of seeing the below error.
At 50K+ rows, I'm yet to see the soft to not crash.
This is the error from the Python terminal.

`Fatal error. Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Python.Runtime.Runtime.PyObject_TYPE(Python.Runtime.BorrowedReference)
   at Python.Runtime.Runtime.PyObject_TYPE(Python.Runtime.BorrowedReference)
   at Python.Runtime.Runtime.NullGCHandles(System.Collections.Generic.IEnumerable`1<IntPtr>)
   at Python.Runtime.Runtime.NullGCHandles(System.Collections.Generic.IEnumerable`1<IntPtr>)
   at Python.Runtime.Runtime.TryCollectingGarbage(Int32, Boolean)
   at Python.Runtime.Runtime.TryCollectingGarbage(Int32, Boolean)
   at Python.Runtime.Runtime.Shutdown()
   at Python.Runtime.Runtime.Shutdown()
   at Python.Runtime.PythonEngine.Shutdown()
   at Python.Runtime.PythonEngine.Shutdown()
   at Python.Runtime.Loader.Shutdown(IntPtr, Int32)
   at Python.Runtime.Loader.Shutdown(IntPtr, Int32)`

I'm using Python 3.10.7

**Comment by DaveSkender** [comment]
It appears that you're exceeding the memory capacity of your computer; but it may also be something unusual with the way we're handling garbage collection.  @LeeDongGeon1996, have any thoughts here?

**Comment by vincehayek** [comment]
Thanks  for your quick reply.
The input file I'm using is below 200Mo and while running the computer is below 20% usage of CPU and RAM.
So I don't think I'm exceeding system capacities.

As for garbage collection, I let Python handle it, I dont have anything specified. 

I'll extract the file from the DB as csv, and prepare a stand alone example so I can share the code and input file with you.

**Comment by DaveSkender** [comment]
> I'll extract the file from the DB as csv, and prepare a stand-alone example to share the code and input file with you.

Your CSV quotes would be helpful for troubleshooting, thank you.  Has this happened on other indicators or just this one?
Hurst Component would be another test to try.

**Comment by LeeDongGeon1996** [comment]
Hi, @vincehayek .
I've tested your code several times and it works well. Every time, It took almost half an hour though.
(I used the same machine as the one for [benchmark](https://python.stockindicators.dev/performance/))

**Comment by vincehayek** [comment]
No it's the exact same one I'm using to reproduce.
The problem might come from my environment.
I will keep you updated if I discover anything.
Thanks for your time.
Keep the good work up!

**Comment by LeeDongGeon1996** [comment]
Yeah, Thank you🙂
If you have any further questions, please reopen or create new issue any time.

**Comment by DaveSkender** [comment]
> [!TIP]
> For a working example using price quotes from a **pandas.DataFrame**, see our [_Replit_ of the Williams Fractal indicator](https://replit.com/@daveskender/Stock-Indicators-for-Python-Williams-Fractal).  If you're having general trouble getting setup, see our [QuickStart guide](https://github.com/DaveSkender/Stock.Indicators.Python.QuickStart#readme).

See also:

- #1165
