### ISSUE TITLE
Does the class Quote only accept Daily-Resolution data?

### ISSUE THREAD

**Issue by stevenpham1996** [DaveSkender/Stock.Indicators.Python#297]
Hi.
I ran into an issue when converting my .csv M1 data to iterable Quote instance.
It seemed like Quote.date only takes Daily-res series but not intraday?
Hope you can assist on a solution.

Much appricated,
Steven

**Comment by LeeDongGeon1996** [comment]
Hi, @stevenpham1996 .
It doesn't restrict to daily data only. You can use intraday series.
If there's error message you got, please share with us.

**Comment by stevenpham1996** [comment]
> Hi Geon/
Thanks for quick reply!
My data is this pandas dataframe
[https://i.imgur.com/v5x9joD.png](url)
I used the list comprehension method suggested in the docs.
[https://i.imgur.com/FlK0ISv.png](url)
And the code got stuck not giving an output though no error messgae either.
Anychance you're aware of the issue?

**Comment by LeeDongGeon1996** [comment]
@stevenpham1996 It's hard to tell you what was wrong with it. When I see the images you uploaded, it seems there's nothing wrong. If you give us more detail, it will be helpful. (e.g. sample code, number of data, which indicator you use)

**Comment by DaveSkender** [comment]
> [!TIP]
> For a working example using price quotes from a **pandas.DataFrame**, see our [_Replit_ of the Williams Fractal indicator](https://replit.com/@daveskender/Stock-Indicators-for-Python-Williams-Fractal).  If you're having general trouble getting setup, see our [QuickStart guide](https://github.com/DaveSkender/Stock.Indicators.Python.QuickStart#readme).

See also:

- #1165
