### ISSUE TITLE
Pivot Points returning no values 

### ISSUE THREAD

**Issue by toncorp** [DaveSkender/Stock.Indicators.Python#299]
First of all, wanted to say thank you for making this, it has some indicators I couldn't find most anywhere else. 

Onto my problem, I'm trying to get pivot points with get_pivot_points, see my below code:

```
pivotpp_quotes_list = [
    Quote(d,o,h,l,c,v) 
    for d,o,h,l,c,v 
    in zip(pd.to_datetime(df.time), df.open, df.high, df.low, df.close, df.Volume)
]

pivotpp = indicators.get_pivot_points(pivotpp_quotes_list, PeriodSize.DAY, PivotPointType.STANDARD)

pivotppresult = []
for r in pivotpp:
    pivotppresult.append(r.pp)

df['PivotPP'] = pivotppresult
```
Forgot to say I also have included these at the top of the code:
```
from stock_indicators import PeriodSize, PivotPointType
from stock_indicators.indicators.common.enums import PeriodSize, PivotPointType
```

I've had no trouble retrieving other indicators using your tool, but for some reason pivot points are giving me trouble. No matter which result I want, s1, pp, etc., the columns in my csv end up blank. I'm certain it's a problem with my code, I'm just not sure what I'm missing. Any help would be appreciated

**Comment by DaveSkender** [comment]
I see you’re using a window size of `PeriodSize.DAY`.  What is the frequency of your quote history?

**Comment by toncorp** [comment]
> I see you’re using a window size of `PeriodSize.DAY`. What is the frequency of your quote history?

I feel dumb, that's it. I'm working with hourly data. Thank you!
