### ISSUE TITLE
Fractals not working.

### ISSUE THREAD

**Issue by jothi-devhub** [DaveSkender/Stock.Indicators.Python#308]
[Sample_Error.csv](https://github.com/DaveSkender/Stock.Indicators.Python/files/11361228/Sample_Error.csv)
### The [problem]([Sample_Error.csv](https://github.com/DaveSkender/Stock.Indicators.Python/files/11361207/Sample_Error.csv))
Hi 

I am trying to create fractal indicator, quotes are obtained from data frame.
Getting results as below:

fractals
<stock_indicators.indicators.fractal.FractalResult object at 0x00000054F93CBD90>
<stock_indicators.indicators.fractal.FractalResult object at 0x00000054F9404880>
<stock_indicators.indicators.fractal.FractalResult object at 0x00000054F94061A0>
<stock_indicators.indicators.fractal.FractalResult object at 0x00000054FA7867D0>

```
#Intitialize Fractal Indicator
quotes = [
    Quote(d,o,h,l,c,v) 
    for d,o,h,l,c,v 
    in zip(rates_frame['time'], rates_frame['open'], rates_frame['high'], rates_frame['low'], rates_frame['close'], rates_frame['tick_volume'])
]

# calculate Fractal
rates_frame['fractal'] = indicators.get_fractal(quotes, 5)

#Save to CSV file
rates_frame.to_csv('Sample_Error.csv')
```

**Comment by LeeDongGeon1996** [comment]
Hi, @jothi-devhub 
It's not a bug. The return value of `get_fractal()` is a list of FractalResults and actual calculated value is stored at `fractal_bear` or `fractal_bull`.

Please refer to https://python.stockindicators.dev/indicators/Fractal/#content .
