### ISSUE TITLE
importing problem

### ISSUE THREAD

**Issue by bahrampasha** [DaveSkender/Stock.Indicators.Python#313]
### The problem

I couldn't import the library and got this error:

ImportError: fail to import clr.
Stock Indicators for Python has dependency on pythonnet, which uses CLR.
Check that you have CLR installed. It's currently using .NET6.

i installed .net 6, pythonnet 3.0.2 as you mentioned, and also ckecked for DOTNET_ROOT.

everything seems OK but i still get this error.

**Comment by DaveSkender** [comment]
If you’re using `homebrew` checkout #309, I think some install methods might not work well.  @LeeDongGeon1996 any thoughts here?

**Comment by bahrampasha** [comment]
couldn't help unfortunately!
I have ubuntu so #309 won't help, anyway i have installed .NET sdk correctly.
i couln't find any help in #298 because  i have already installed requirements.txt

**Comment by DaveSkender** [comment]
@LeeDongGeon1996 I see we [reference](https://github.com/DaveSkender/Stock.Indicators.Python/blob/6e2fd9bcdebb18cd481b7efc4a3fe54f8e6b0da0/stock_indicators/_cslib/runtimeconfig.json#L6)  .NET `6.0.0`, can we set this with a wildcard `6.x` or are we missing [this PythonNET recommendation](https://github.com/pythonnet/pythonnet#net-core)?

**Comment by LeeDongGeon1996** [comment]
> All runtime implementations can be initialized without additional parameters. While previous versions of clr_loader required a runtimeconfig.json to load .NET Core, this requirement was lifted for the version used in pythonnet.

They updated clr_loader, and now we don't need runtimeconfig.json anymore. I'll have a test on this.

**Comment by LeeDongGeon1996** [comment]
I think this problem may be solved in out latest version, v1.1.0. Please re-open or create new issue if you're still having trouble
