### ISSUE TITLE
incompatible test.pypi.org version number

### ISSUE THREAD

**Issue by DaveSkender** [DaveSkender/Stock.Indicators.Python#325]
### The problem

When publishing to the `test.pypi.org` package manager, it's expecting `PEP 440` standard version numbers, whereas we're using `SemVer` standards that allow for pre-release suffixes.  See [deployment](https://github.com/DaveSkender/Stock.Indicators.Python/actions/runs/7327940125/job/19955500913#step:4:24), related to #322

Error message:

```bash
ERROR    HTTPError: 400 Bad Request from https://test.pypi.org/legacy/          
         '0.1.dev1+gb71369a' is an invalid value for Version. Error: Can't use  
         PEP 440 local versions. See                                            
         https://packaging.python.org/specifications/core-metadata for more     
         information.       
```

**Comment by LeeDongGeon1996** [comment]
This will be fixed at [41ddd3c](https://github.com/DaveSkender/Stock.Indicators.Python/pull/326/commits/41ddd3ccdd541281763fe0a9e2d0ea9303529424)
