### ISSUE TITLE
Add Dominant Cycle Periods to HT Trendline

### ISSUE THREAD

**Issue by LeeDongGeon1996** [DaveSkender/Stock.Indicators.Python#340]
- https://github.com/DaveSkender/Stock.Indicators/pull/948 (v2.4.1)

**Comment by LeeDongGeon1996** [comment]
@DaveSkender  Can you force-remove this issue?

**Comment by DaveSkender** [comment]
Duplicate of #338

**Comment by DaveSkender** [comment]
I can fully delete too if desired, but just marked it as closed/duplicate initially.
