### ISSUE TITLE
help: getting empty values with Williams Fractal

### ISSUE THREAD

**Issue by Waldi2130** [DaveSkender/Stock.Indicators.Python#346]
Hello, very much in need of help, the third day I can not determine the cause, my indicators do not work, I pass to begin with information for 200 candlesticks, then the program adds each time new candlesticks, I do not get errors in the code, but when I try to get a fractal, they are always empty, the same with some indicators, let's say sma.
I am using Windows 10, NET 6.0 and NET 8.0, mono installed, Python 3.11.8.
The first 200 candles are recorded normally, then I add new ones like this:
1707408420 | 0.89531 | 0.89531 | 0.89531 | 0.89531

![image](https://github.com/DaveSkender/Stock.Indicators.Python/assets/41347054/7009bfa3-ace0-48c6-a26b-3063fd8c0c6e)
![image](https://github.com/DaveSkender/Stock.Indicators.Python/assets/41347054/eda27846-bde4-4909-90ff-613d61ec8679)

**Comment by DaveSkender** [comment]
This may just be an interpretation problem with the results of [Williams Fractal](https://python.stockindicators.dev/indicators/Fractal/#returns).  The bull points and bear points are maintained in separate datasets because it's technically feasible that there'd be bear and bull event on the same date if the candle is long.  If you plotted these two datasets, it'd look something like this these green/red dots:

![image](https://github.com/DaveSkender/Stock.Indicators.Python/assets/8432125/40b23b83-da11-4844-839d-e21008bed580)

**Comment by Waldi2130** [comment]
Just another guy's mac has them working fine, that's why I'm trying to figure it out. and the code is the same as mine.

**Comment by DaveSkender** [comment]
> Just another guy's mac has them working fine, that's why I'm trying to figure it out. and the code is the same as mine.

It does seem odd that you're parsing these differently with `os.name`.  Are you stuck on simply parsing quotes into a usable set?  It'd be helpful to see more about your raw quote sources.  Can you try to print them to console, without complicating it with the extra _fractal_ calculation, just to see if the quotes themselves are loading okay?

**Comment by Waldi2130** [comment]
![image](https://github.com/DaveSkender/Stock.Indicators.Python/assets/41347054/a9e03559-db49-40ec-a60b-4a7d8c0b778b)
I have now tried getting data from the Chandelier Exit indicator, as you can see in the console, it comes in and works out.

**Comment by Waldi2130** [comment]
![image](https://github.com/DaveSkender/Stock.Indicators.Python/assets/41347054/bed045ea-f334-40ba-b8cf-569e16f5574e)
Also, I tried to remove os.name, when I did this, I stopped working and the rest of the indicators and the program no longer displays anything

**Comment by Waldi2130** [comment]
![image](https://github.com/DaveSkender/Stock.Indicators.Python/assets/41347054/bbab40a5-8591-4a08-befc-a4e8111e6d54)
This is my initial data I'm getting, it's about 200 lines of data.

**Comment by DaveSkender** [comment]
I don't see anything weird with your `CANDLES` values.
![image](https://github.com/DaveSkender/Stock.Indicators.Python/assets/8432125/6be03c91-7a72-47b0-83fd-4affa9b82bb6)

What do your `quotes` look like after parsing them?

**Comment by Waldi2130** [comment]
![image](https://github.com/DaveSkender/Stock.Indicators.Python/assets/41347054/c0e1ce35-8e4b-4c4f-8690-a7af35725a20)

this is what you get when you record

**Comment by DaveSkender** [comment]
It is possible to get no results with a short quotes dataset on those two indicators if there’s no identifying trend reversals.  If you upload those quotes, I’ll take a closer look when I have some time.

**Comment by Waldi2130** [comment]
I can upload you a csv file with 200 lines of candle data.
I also tested leaving the program running for a day to collect more than 200 lines, but when I checked, the data was always empty. I will try to do another test.
I just can't understand how the other guy's code can work and I can't.

**Comment by Waldi2130** [comment]
[EURGBP_2024_2_8_19.csv](https://github.com/DaveSkender/Stock.Indicators.Python/files/14213739/EURGBP_2024_2_8_19.csv)

**Comment by DaveSkender** [comment]
> other guy's code can work and I can't.

For clarity, is he using the exact same quotes dataset?

**Comment by Waldi2130** [comment]
I still haven't been able to find a solution to the problem. 
Tell me, did you have time to check it out?
Thank you.

**Comment by DaveSkender** [comment]
So far, I've done two things to rule to rule out the core algorithm:

1. Run these quotes through our manual calculations » [Fractal.Calc.Issue346.xlsx](https://github.com/DaveSkender/Stock.Indicators.Python/files/14230480/Fractal.Calc.Issue346.xlsx)

2. Run these quotes through our core .NET library » https://dotnetfiddle.net/9l1AUR

There are no issues there, but I think we already know that.  For a quick check, I converted `.` to `,` in the spreadsheet and it produced bad results; but I expected that because I'm not running on European localization settings on my Windows PC.

Current hypothesis is kindof the same for me: it has something to do with the way you're converting quotes, and what the library understands.  What I'm trying to figure out if there's some localization fixes we can do in the Python library to make accommodate localized number formats -- or, if this is just something in your conversion code.

**Comment by DaveSkender** [comment]
Before I spend more time on this, can you check to make sure you're mapping the fields with the correct index?

```csv
# what you provided
,timestamp,open,close,high,low
0,1707408960.0,0.8955,0.89622,0.89622,0.89536
1,1707409020.0,0.89622,0.89697,0.89699,0.89597
2,1707409080.0,0.89697,0.89644,0.89697,0.8964
...
```
Would mean your field mapping should be:

```python
...
  for candles in CANDLES:
    open = candle[2]
    close = candle[3]
    high = candle[4]
    low = candle[5]
...
```

**Comment by Waldi2130** [comment]
Hello, yes, I am mapping to the correct index, I have attached a screenshot, I also wrote the resulting data to csv to show it to you.
![image](https://github.com/DaveSkender/Stock.Indicators.Python/assets/41347054/39cfc861-ae12-4218-80ed-e8d3fe37d475)

**Comment by LeeDongGeon1996** [comment]
Sorry, but it's hard to understand where the `payload_str` came from, what `PERIOD` value is, and why `CANDES` 's indexing is starting from 0.

**Comment by Waldi2130** [comment]
![image](https://github.com/DaveSkender/Stock.Indicators.Python/assets/41347054/aceca9dd-8ab4-4e75-b388-acae7208d8f1)
Oh, I didn't clarify that point, please forgive me.
I get this data directly from the graph via websocket and chromedriver. They are constantly updated and after a while they give me the last 200 candles and constant information about new candles.

**Comment by DaveSkender** [comment]
Oh … I think I see what you were expecting.  The current version of our library doesn’t yet support observable streaming use cases, it’s a basic converter of `quotes`, so adding a new `quote` does not automatically generate a new _indicator value_ unless you recalculate the set by repeating `results=indicators.get_fractal(quotes)`.

Our next major version will focus on incremental and streaming data use cases.

**Comment by DaveSkender** [comment]
@Waldi2130 if you need more help here, let us know, or close this issue.
