### ISSUE TITLE
ROC is missing `Momentum` return value

### ISSUE THREAD

**Issue by hmuhdkamran** [DaveSkender/Stock.Indicators.Python#353]
### The problem

in indicator roc.py has missing momentum, you should add the following lines in it

Error message(s):

```bash
    @property
    def momentum(self) -> Optional[float]:
        return self._csdata.Momentum

    @momentum.setter
    def roc_sma(self, value):
        self._csdata.Momentum = value
```

**Comment by DaveSkender** [comment]
@LeeDongGeon1996 do you want to sneak this into your next release?

**Comment by LeeDongGeon1996** [comment]
@hmuhdkamran Thank you for reporting. I'll include this feature in this release.
