### ISSUE TITLE
an ALL parameter to calc the all indicators with default parameter

### ISSUE THREAD

**Issue by luigif2000** [DaveSkender/Stock.Indicators.Python#358]
Dear,
is there the possibility to have ALL the indicators created with only a few lines?

this feature could be very very useful.

thanks in advance and waiting a kindly reply.

luigif

**Comment by LeeDongGeon1996** [comment]
You can use `inspect` module. But be careful that not every indicator methods have default parameter value.
```python
import inspect
import stock_indicators.indicators as indicators

all_indicator_methods = inspect.getmembers(indicators, inspect.isfunction)
for indicator_method in all_indicator_methods:
    # call and do somthing here.
```

**Comment by luigif2000** [comment]
thanks...that's very kind of You!!
Best regards.

luigi
