### ISSUE TITLE
Auto-increment versions in build

### ISSUE THREAD

**Issue by DaveSkender** [DaveSkender/Stock.Indicators.Python#38]
One thing I'm going to want to do in the build before we do a public publish is to auto-update the version number in the build process.  The `GitVersion` build task produces an environment variable `$(GitVersion.MajorMinorPatch)` that I think we can use to text replace  `version="0.0.0"` in `setup.py`.  I'm not sure of the best way to do that with Python commands; however, the worst case is we just do a straight text replacement in the `setup.py` file in the build process.  I'd like the build system to manage the version numbers and not rely on manually updating `setup.py`.

Ref: https://gitversion.net/docs/reference/variables
Observed in #28

**Comment by LeeDongGeon1996** [comment]
@DaveSkender Works well!

**Comment by DaveSkender** [comment]
When I get a moment, I’ll setup the test PyPI and regular PyPI account endpoints.
