### ISSUE TITLE
Init documentation

### ISSUE THREAD

**Issue by LeeDongGeon1996** [DaveSkender/Stock.Indicators.Python#51]
I think that, for the documentation for Python version, what we just need to do is fine-tuning its C# documentation. So I'm going to copy doc files to start writing docs. So it'll be appreciated if you can setup github-page so that we can see the preview while writing. Is there any other thought about it?

**Comment by DaveSkender** [comment]
Yeah, I think we just copy that `docs` folder over (and remove indicators we haven't implemented yet), then tweak to reflect Python syntax usage.  You should be able to build and view the site locally by following the instructions in `contributing.md`.  I can turn on GitHub Pages when we're ready to deploy a public site.  A couple of thoughts:

1. I'd suggest we leave the Discussion links going to the `Stock.Indicators` library pages; though can be convinced to either just drop that link on the individual pages.
2. Change the URL to the chart images to just pull from the `Stock.Indicators` library so we don't need redundant copies.  We'd done this in the current `main` branch `README.md`, as an example.
