### ISSUE TITLE
Initial release v0.1.0

### ISSUE THREAD

**Issue by DaveSkender** [DaveSkender/Stock.Indicators.Python#62]
@LeeDongGeon1996 now that you've been able to establish a decent baseline approach, let's discuss some of the next steps towards an initial release and making the repo public.  I'd like to do this once we have a core of about 15 of the most popular indicators implemented and working well so we can both start getting user feedback and potentially more community contribution.

To get to an initial v0.1.0 launch, here's what I think we need:

- [x] 10-15 of the most popular indicators (I've sorted these in [the Backlog](https://github.com/DaveSkender/Stock.Indicators.Python/projects/1))
- [x] Build that produces unit tests, code coverage, and a candidate release package
- [x] #38
- [x] General documentation on usage - #53 
- [x] Release to [Internal package manager](https://dev.azure.com/skender/Stock.Indicators/_packaging?_a=package&feed=Internal%40Local&package=stock-indicators&protocolType=PyPI) on Azure Artifacts -- this will allow us to get a true Preview and end-use scenario
- [x] Make repo public
- [x] Final sanity check on the usability of the actual package
- [x] Finalize release pipeline and release to PyPI
- [x] add links to PyPI page in docs and launch doc site - #73 
- [x] Move on, to implement full register of indicators

After we get there, we'll have a good pipeline approach to doing periodic batch releases.  Thoughts?

**Comment by DaveSkender** [comment]
@LeeDongGeon1996 let's do a final sanity check on the package from the end-users perspective.  Have you tried to download (internal) and use it, and are comfortable with usability?  Once we wrap up docs, I think we can publish this initial release, as long as the package is solid.

**Comment by LeeDongGeon1996** [comment]
Yeah, I tried and there's no any difficulties or trouble. Also, the indicator methods are very simple so that, with our documentation, users can easily get the results from it. 

Plus, we need to release newer package including latest changes to Internal. It can allow us to test latest package from users perspective.

**Comment by DaveSkender** [comment]
Go ahead and publish to Internal if you think we have a release candidate.  I’ve merged the doc site branch.

**Comment by LeeDongGeon1996** [comment]
That's great. 👍

**Comment by DaveSkender** [comment]
I’ll take a look at getting the deployment pipeline finalized tomorrow, it’s getting late here … 3am 🤪.  After you check the package, let me know if we need to add anymore checklist items above.  If not, I’ll work through the rest, including actual deployment to PyPI.

**Comment by LeeDongGeon1996** [comment]
Oh, it's too late. Take a rest 😄. I'll have a look if there's something more to be done.

**Comment by LeeDongGeon1996** [comment]
1. Cannot release to Internal.
    The version of package is calculated by gitversion and current version is fixed as 0.1.0, which we are going to release to public.  In this case, I need to release v0.0.2 for end-user testing, but currently we can't specify its version by ourselves. Release pipeline uses Artifacts with the version(0.1.0) from gitversion.
    To resolve, we need to change pipelines, or maybe emptying recycle bin can be solution.

**Comment by DaveSkender** [comment]
See if you can deploy the last PR build instead:
https://dev.azure.com/skender/Stock.Indicators/_build/results?buildId=3839&view=results

**Comment by DaveSkender** [comment]
For now, I've just deployed it to PyPI test site: https://test.pypi.org/project/stock-indicators/
Give it shot and I'll deploy to the full site if it's working okay for you.

**Comment by DaveSkender** [comment]
Also, send me your PyPI.org username and I'll add you as a Maintainer.

**Comment by DaveSkender** [comment]
I just went ahead and released it.  Worst case, we bump to a 0.1.1 version quickly if there are problems.
https://pypi.org/project/stock-indicators/

**Comment by LeeDongGeon1996** [comment]
@DaveSkender Wonderful!!😆 Finally, we did it. It was nice to work together. Let's keep our working and make it better.

My PyPI: LeeDongGeon1996

**Comment by DaveSkender** [comment]
@LeeDongGeon1996 feel free to close this if you've done your sanity check on it.
