### ISSUE TITLE
Can't call overloaded method with template parameters

### ISSUE THREAD

**Issue by LeeDongGeon1996** [DaveSkender/Stock.Indicators.Python#82]
## Problem

There's still no way to call methods with template parameters.

 - parabolic SAR
 - ichimoku
 - gator
 - Williams Fractal

## Related issue

- https://github.com/pythonnet/pythonnet/issues/1522

**Comment by LeeDongGeon1996** [comment]
@DaveSkender Could you combine two overloaded interface of `GetEMA()` if there's no problem. Then we can support `CandlePart` as its parameter with current pythonnet version.

**Comment by DaveSkender** [comment]
I’ll take a look

**Comment by LeeDongGeon1996** [comment]
@DaveSkender Thanks

**Comment by LeeDongGeon1996** [comment]
Fixed.
